version: '2'
.catalog:
  name: Minio
  version: 2017-03-16-rancher1
  questions:
    - variable: "VOLUME_DRIVER"
      description: "Docker driver to store volume or base path for each disks"
      label: "Volume drver / Path"
      type: "string"
      required: true
      default: "local"
    - variable: "MINIO_DISKS"
      description: "Number of disks per node"
      label: "Disks Per Node"
      required: true
      type: enum
      default: 1
      options:
        - 1
        - 2
        - 4

services: 
  minio-server:
    scale: ${MINIO_SCALE}
    retain_ip: true
    health_check:
      port: 9000
      interval: 5000
      unhealthy_threshold: 3
      request_line: ''
      healthy_threshold: 2
      response_timeout: 5000