version: '2'
.catalog:
  name: Minio
  version: 2017-03-16-rancher1
  questions:
    - variable: "MINIO_DISKS"
      description: "Number of disks per node"
      label: "Disks Per Node"
      required: true
      type: enum
      default: 1
      options:
        - 1
        - 2
        - 4
    - variable: "VOLUME_DRIVER"
      description: "Docker driver to store volume or base path for each disks"
      label: "Volume drver / Path"
      type: "string"
      required: true
      default: "local"